---
deployment:
  tasks:
    - source /home/deployment/environment.rc
    - npm i
    - npm run build
    - rm -rf $DEPLOYPATH
    - mv build $DEPLOYPATH
    - rm -rf $APIPATH
    - cp src/server $APIPATH
